/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedOutwardIndexRouteImport } from './routes/_authenticated/outward.index'
import { Route as AuthenticatedInwardIndexRouteImport } from './routes/_authenticated/inward.index'
import { Route as AuthenticatedInwardVendorIdRouteImport } from './routes/_authenticated/inward.$vendorId'
import { Route as AuthenticatedOutwardPartyIdIndexRouteImport } from './routes/_authenticated/outward.$partyId.index'
import { Route as AuthenticatedOutwardPartyIdOrderIdRouteImport } from './routes/_authenticated/outward.$partyId.$orderId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutwardIndexRoute =
  AuthenticatedOutwardIndexRouteImport.update({
    id: '/outward/',
    path: '/outward/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInwardIndexRoute =
  AuthenticatedInwardIndexRouteImport.update({
    id: '/inward/',
    path: '/inward/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInwardVendorIdRoute =
  AuthenticatedInwardVendorIdRouteImport.update({
    id: '/inward/$vendorId',
    path: '/inward/$vendorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutwardPartyIdIndexRoute =
  AuthenticatedOutwardPartyIdIndexRouteImport.update({
    id: '/outward/$partyId/',
    path: '/outward/$partyId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutwardPartyIdOrderIdRoute =
  AuthenticatedOutwardPartyIdOrderIdRouteImport.update({
    id: '/outward/$partyId/$orderId',
    path: '/outward/$partyId/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inward/$vendorId': typeof AuthenticatedInwardVendorIdRoute
  '/inward/': typeof AuthenticatedInwardIndexRoute
  '/outward/': typeof AuthenticatedOutwardIndexRoute
  '/outward/$partyId/$orderId': typeof AuthenticatedOutwardPartyIdOrderIdRoute
  '/outward/$partyId/': typeof AuthenticatedOutwardPartyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inward/$vendorId': typeof AuthenticatedInwardVendorIdRoute
  '/inward': typeof AuthenticatedInwardIndexRoute
  '/outward': typeof AuthenticatedOutwardIndexRoute
  '/outward/$partyId/$orderId': typeof AuthenticatedOutwardPartyIdOrderIdRoute
  '/outward/$partyId': typeof AuthenticatedOutwardPartyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inward/$vendorId': typeof AuthenticatedInwardVendorIdRoute
  '/_authenticated/inward/': typeof AuthenticatedInwardIndexRoute
  '/_authenticated/outward/': typeof AuthenticatedOutwardIndexRoute
  '/_authenticated/outward/$partyId/$orderId': typeof AuthenticatedOutwardPartyIdOrderIdRoute
  '/_authenticated/outward/$partyId/': typeof AuthenticatedOutwardPartyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/inward/$vendorId'
    | '/inward/'
    | '/outward/'
    | '/outward/$partyId/$orderId'
    | '/outward/$partyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/inward/$vendorId'
    | '/inward'
    | '/outward'
    | '/outward/$partyId/$orderId'
    | '/outward/$partyId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/inward/$vendorId'
    | '/_authenticated/inward/'
    | '/_authenticated/outward/'
    | '/_authenticated/outward/$partyId/$orderId'
    | '/_authenticated/outward/$partyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outward/': {
      id: '/_authenticated/outward/'
      path: '/outward'
      fullPath: '/outward/'
      preLoaderRoute: typeof AuthenticatedOutwardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inward/': {
      id: '/_authenticated/inward/'
      path: '/inward'
      fullPath: '/inward/'
      preLoaderRoute: typeof AuthenticatedInwardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inward/$vendorId': {
      id: '/_authenticated/inward/$vendorId'
      path: '/inward/$vendorId'
      fullPath: '/inward/$vendorId'
      preLoaderRoute: typeof AuthenticatedInwardVendorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outward/$partyId/': {
      id: '/_authenticated/outward/$partyId/'
      path: '/outward/$partyId'
      fullPath: '/outward/$partyId/'
      preLoaderRoute: typeof AuthenticatedOutwardPartyIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outward/$partyId/$orderId': {
      id: '/_authenticated/outward/$partyId/$orderId'
      path: '/outward/$partyId/$orderId'
      fullPath: '/outward/$partyId/$orderId'
      preLoaderRoute: typeof AuthenticatedOutwardPartyIdOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInwardVendorIdRoute: typeof AuthenticatedInwardVendorIdRoute
  AuthenticatedInwardIndexRoute: typeof AuthenticatedInwardIndexRoute
  AuthenticatedOutwardIndexRoute: typeof AuthenticatedOutwardIndexRoute
  AuthenticatedOutwardPartyIdOrderIdRoute: typeof AuthenticatedOutwardPartyIdOrderIdRoute
  AuthenticatedOutwardPartyIdIndexRoute: typeof AuthenticatedOutwardPartyIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInwardVendorIdRoute: AuthenticatedInwardVendorIdRoute,
  AuthenticatedInwardIndexRoute: AuthenticatedInwardIndexRoute,
  AuthenticatedOutwardIndexRoute: AuthenticatedOutwardIndexRoute,
  AuthenticatedOutwardPartyIdOrderIdRoute:
    AuthenticatedOutwardPartyIdOrderIdRoute,
  AuthenticatedOutwardPartyIdIndexRoute: AuthenticatedOutwardPartyIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
